In [ ]:
# In later parts, we will see how to:

# Create a tensor with tf.constant()
# Create a tensor with tf.variable()
# Create tensors from existing functions
# Select data in a tensor
# Perform operations in tensor
# Manipulate tensor shape

In [ ]:
#  Creating a Tensor with tf.constant()

In [1]:
# I will first import tensorflow as tf
# Also import numpy as np
# If you are using Colab, no need to install them 

import tensorflow as tf
import numpy as np

In [2]:
# Creating a scalar tensor
# You can specify dtype but TF will detect its if left unspecified

scalar_tensor = tf.constant(10)

In [3]:
# Displaying created tensor

print(scalar_tensor)

tf.Tensor(10, shape=(), dtype=int32)


In [4]:
# We can also create a vector or rank 1 tensor
# Simply put, a vector is one dimensional
# We can create it from a list of values

vect_tensor = tf.constant([1.0,2.0,3.0,4.0,5.0,6.0])

In [5]:
print(vect_tensor)

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)


In [7]:
mat_tensor = tf.constant([[2,4],
                         [6,8],
                         [10,12]], dtype=tf.int32)

In [8]:
print(mat_tensor)

tf.Tensor(
[[ 2  4]
 [ 6  8]
 [10 12]], shape=(3, 2), dtype=int32)


In [9]:
scalar_tensor.ndim

0

In [10]:
# A vector has 1 dimension

vect_tensor.ndim

1

In [11]:
# A matrix has 2D or more dimensions

mat_tensor.ndim

2

In [12]:
tensor_3d = tf.constant([
                         [[1,2,3,4,5],
                         [6,7,8,9,8]],
                         [[1,3,5,7,9],
                         [2,4,6,8,1]],
                         [[1,2,3,5,4],
                         [3,4,5,6,7]], ])

print(tensor_3d)

tf.Tensor(
[[[1 2 3 4 5]
  [6 7 8 9 8]]

 [[1 3 5 7 9]
  [2 4 6 8 1]]

 [[1 2 3 5 4]
  [3 4 5 6 7]]], shape=(3, 2, 5), dtype=int32)


In [13]:
tensor_3d.ndim

3

In [14]:
# Converting a tensor into a NumPy array

n_array = tensor_3d.numpy()

n_array

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 8]],

       [[1, 3, 5, 7, 9],
        [2, 4, 6, 8, 1]],

       [[1, 2, 3, 5, 4],
        [3, 4, 5, 6, 7]]], dtype=int32)

In [ ]:
# Using np.array(tensor_name)

np.array(tensor_3d)

In [ ]:
# .item(3)

In [15]:
var_tensor = tf.Variable([
                         [[1,2,3,4,5],
                         [6,7,8,9,8]],
                         [[1,3,5,7,9],
                         [2,4,6,8,1]],
                         [[1,2,3,5,4],
                         [3,4,5,6,7]], ])

print(var_tensor)

<tf.Variable 'Variable:0' shape=(3, 2, 5) dtype=int32, numpy=
array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 8]],

       [[1, 3, 5, 7, 9],
        [2, 4, 6, 8, 1]],

       [[1, 2, 3, 5, 4],
        [3, 4, 5, 6, 7]]], dtype=int32)>


In [16]:
# Converting a variable tensor into NumPy array

var_tensor.numpy()

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 8]],

       [[1, 3, 5, 7, 9],
        [2, 4, 6, 8, 1]],

       [[1, 2, 3, 5, 4],
        [3, 4, 5, 6, 7]]], dtype=int32)

In [17]:
 #Creating a Tensor from Existing Functions

In [18]:
# Creating 1's tensor

ones_tensor = tf.ones([4,4])

print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)


In [19]:
# Creating 1's tensor

ones_tensor_1 = tf.ones([1,10])

print(ones_tensor_1)

tf.Tensor([[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(1, 10), dtype=float32)


In [20]:
# Creating zeros' tensor

tensor_0 = tf.zeros([3,3])
print(tensor_0)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [21]:
# Generating a tensor with random values 

# We first have to create a generator object

rand_tensor = tf.random.Generator.from_seed(3)

rand_tensor = rand_tensor.normal(shape=[3,3])
print(rand_tensor)

tf.Tensor(
[[-0.43640924 -1.9633987  -0.06452483]
 [-1.056841    1.0019137   0.6735137 ]
 [ 0.06987712 -1.4077919   1.0278524 ]], shape=(3, 3), dtype=float32)


In [22]:
# Create a typical tensor 

example_tensor = tf.constant([[1,3],
                             [3,4],
                             [4,5]])

print(example_tensor)

tf.Tensor(
[[1 3]
 [3 4]
 [4 5]], shape=(3, 2), dtype=int32)


In [23]:
def shuffle_tensor(tensor):

  """
  Take a tensor as input and return the shuffled tensor
  """
  # Shuffle the order of the created tensor

  tensor_shuffled = tf.random.shuffle(tensor)

  return print(tensor_shuffled)

In [24]:
shuffle_tensor(example_tensor)

tf.Tensor(
[[3 4]
 [4 5]
 [1 3]], shape=(3, 2), dtype=int32)


In [25]:
# Set seed 

tf.random.set_seed(42)

shuffle_tensor(example_tensor)

tf.Tensor(
[[3 4]
 [4 5]
 [1 3]], shape=(3, 2), dtype=int32)


In [26]:
#Selecting Data in Tensor

In [27]:
# Let's create a tensor

tensor_1d = tf.constant([1,2,3,4,5,6,7])

In [28]:
print('The first value:', tensor_1d[0].numpy())
print('The second value:', tensor_1d[2].numpy())
print('From the 3 to 5th values:', tensor_1d[3:5].numpy())
print('From the 3 to last value:', tensor_1d[3:].numpy())
print('The last value:', tensor_1d[-1].numpy())
print('Select value before the last value:', tensor_1d[-2].numpy())
print('Select all tensor values:', tensor_1d[:].numpy())

The first value: 1
The second value: 3
From the 3 to 5th values: [4 5]
From the 3 to last value: [4 5 6 7]
The last value: 7
Select value before the last value: 6
Select all tensor values: [1 2 3 4 5 6 7]


In [29]:
tensor_2d = tf.constant([[1,3],
                          [3,4],
                          [4,5]])

In [30]:
print('The first row:', tensor_2d[0,:].numpy())
print('The second column:', tensor_2d[:,1].numpy())
print('The last low:', tensor_2d[-1,:].numpy())
print('The first value in the last row:', tensor_2d[-1,0].numpy())
print('The last value in the last column:', tensor_2d[-1,-1].numpy())

The first row: [1 3]
The second column: [3 4 5]
The last low: [4 5]
The first value in the last row: 4
The last value in the last column: 5


In [31]:
#Performing Operations on Tensors

In [32]:
# Creating example tensors 

tensor_1 = tf.constant([1,2,3])
tensor_2 = tf.constant([4,5,6])

In [33]:
# Adding a scalar value to a tensor

print(tensor_1 + 4)

tf.Tensor([5 6 7], shape=(3,), dtype=int32)


In [34]:
# Adding two tensors 

print(tensor_1 + tensor_2)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [35]:
# Can also add with tf.add() or tf.math.add()

print(tf.add(tensor_1, tensor_2))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [36]:
# multiplying tensors with tf.multiply()

print(tf.multiply(tensor_1, tensor_2))

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [37]:
# Manipulating the Shape of Tensor

In [38]:
print(example_tensor)

tf.Tensor(
[[1 3]
 [3 4]
 [4 5]], shape=(3, 2), dtype=int32)


In [39]:
tens_reshaped = tf.reshape(example_tensor, [2,3])

In [40]:
print(tens_reshaped)

tf.Tensor(
[[1 3 3]
 [4 4 5]], shape=(2, 3), dtype=int32)


In [41]:
# Also to (6,1)

print(tf.reshape(example_tensor, [6,1]))

tf.Tensor(
[[1]
 [3]
 [3]
 [4]
 [4]
 [5]], shape=(6, 1), dtype=int32)


In [42]:
# You can also shape a tensor into a list

print(example_tensor.shape.as_list())

[3, 2]


In [43]:
# You can also flatten a tensor

print(tf.reshape(example_tensor, [-1]))

tf.Tensor([1 3 3 4 4 5], shape=(6,), dtype=int32)
